TWILIO_ACCOUNT_SID: <%= Rails.application.credentials.dig(:twilio, :account_sid) %>
TWILIO_AUTH_TOKEN: <%= Rails.application.credentials.dig(:twilio, :auth_token) %>
TWILIO_MSG_SERVICE_ID: <%= Rails.application.credentials.dig(:twilio, :msg_service_id) %>